include:
  - project: 'grandlinex/templates'
    file: '/stages.yml'
  - project: 'grandlinex/templates'
    file: '/prod/core-bundle.yml'
  - project: 'grandlinex/templates'
    file: '/build/core-bundle.yml'
  - project: 'grandlinex/templates'
    file: '/sonar/core-sonar.yml'
  - project: 'grandlinex/templates'
    file: '/deploy/npm-deploy.yml'
  - project: 'grandlinex/templates'
    file: '/update/update-glx.yml'
  - project: 'grandlinex/templates'
    file: '/deploy/npm-gitlab-deploy.yml'
  - project: 'grandlinex/templates'
    file: '/test/sast.yml'
